language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install multimethod pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  user: coady
  password:
    secure: AkJEAtOY5s878pjLF16vLWHVXD+38rwBpPoGFUnb7S1x17w40+Wnt+r6AF8xEK6TGXn7x/lbFjIpULUwhzcB4Qzj6WOBTtPBipCVM9D/LQwUnzpE1ZrN0G7QfcN3DkwLnIQcVwLJ4t8qUVOC21nc3sHGoaZ+vMrAhVdnBcpM5iIgMlRcNRhIePAIarEfCE+8FnGwGRyDilzWNwVB6EJezTEaJpQd+raNFU4LByWk2J67AhSgPED5PoOHObhDL2A51qK/SGmj1G96kNi30IGFOBBnvPlChoLFE2n6qi9H09btQS4RgLYd21cAnypxnE/gOJvA8en+hIYglENuvJkmWgIelepQi65RTOnaDPRJkTo58HNwbtf5Ws9jPkOMHK5zAvOqC8XornzgtTGu6Vv5pBGaV7GUjivBjYuGPwikCG4INXYk2sJa6EQA4447W61arQy2Waw/1yTaRqOz96pahJqtYd43VeLq0yBpIs3jhCTFrTEoenK5+usNhJ5VnT2gl4/HSJZfXaCR391DBOe9sWkLkDIkO+Qnrm+pwzyREFjBVrUvLpMu0T438qj3rGrUqVlPZ+bDkOaJTibCeWwAUGnBpZ8SxoEdl6a5chRrLPeD8hcTJNeadC5lTRj3JuKLYseE/Jpyhk4srK2EqfRDHGeykfnRxhdAMYNJBb7KIDc=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
