site_name: waiter
site_url: https://coady.github.io/waiter/
site_description: Delayed iteration for polling and retries.
theme: material

repo_name: coady/waiter
repo_url: https://github.com/coady/waiter
edit_uri: ""

nav:
  - Introduction: index.md
  - Reference: reference.md
  - Examples: examples.ipynb

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
